[package]
name = "rdaw"
version = "0.1.0"
edition = "2021"

[dependencies]
rdaw-backend.workspace = true
rdaw-frontend.workspace = true

futures-lite.workspace = true
tracing-subscriber.workspace = true
