[package]
name = "rdaw"
version = "0.1.0"
edition = "2021"

[dependencies]
rdaw-backend.workspace = true
rdaw-frontend.workspace = true
rdaw-rpc.workspace = true

futures.workspace = true
tracing-error.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
