[package]
name = "rdaw-pipewire"
version = "0.1.0"
edition = "2021"

[dependencies]
rdaw-api.workspace = true
rdaw-audio.workspace = true

oneshot.workspace = true
pipewire.workspace = true
slotmap.workspace = true
thiserror.workspace = true
tracing.workspace = true
