use_field_init_shorthand = true
newline_style = "Unix"

unstable_features = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
wrap_comments = true
comment_width = 100
normalize_comments = true
normalize_doc_attributes = true
