[package]
name = "rdaw-audio"
version = "0.1.0"
edition = "2021"

[dependencies]
rdaw-api.workspace = true
rdaw-core.workspace = true

bumpalo.workspace = true
slotmap.workspace = true
smallvec.workspace = true
