[package]
name = "rdaw-core"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-utils.workspace = true
shared_memory.workspace = true
thiserror.workspace = true

[target.'cfg(loom)'.dependencies]
loom.workspace = true
