[package]
name = "rdaw-core"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-utils.workspace = true
nix = { version = "0.28.0", features = ["fs", "mman"] }
rand = "0.8.5"
shared_memory.workspace = true
thiserror.workspace = true
tracing.workspace = true

[target.'cfg(loom)'.dependencies]
loom.workspace = true
