[package]
name = "rdaw-object"
version = "0.1.0"
edition = "2021"

[dependencies]
rdaw-api.workspace = true
rdaw-core.workspace = true

blake3.workspace = true
rstar.workspace = true
slotmap.workspace = true
uuid.workspace = true

[dev-dependencies]
rand.workspace = true
