[package]
name = "rdaw-object"
version = "0.1.0"
edition = "2021"

[dependencies]
rdaw-core.workspace = true

rstar.workspace = true
slotmap.workspace = true

[dev-dependencies]
rand.workspace = true
