[package]
name = "rdaw-api"
version = "0.1.0"
edition = "2021"

[dependencies]
rdaw-core.workspace = true

futures-lite.workspace = true
slotmap.workspace = true
thiserror.workspace = true
trait-variant.workspace = true
