[package]
name = "rdaw-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
rdaw-api.workspace = true
rdaw-core.workspace = true
rdaw-ui.workspace = true

floem.workspace = true
futures.workspace = true
im.workspace = true
tracing.workspace = true
